# Generated by Django 4.1 on 2022-08-05 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_jobpost_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='지원날짜')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.jobpost', verbose_name='채용공고')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='지원자')),
            ],
            options={
                'db_table': 'applies',
            },
        ),
    ]
